bindsym XF86AudioLowerVolume exec --no-startup-id $DOTFILES/bin/host-specific/nixnode/volume-osd down
bindsym XF86AudioRaiseVolume exec --no-startup-id $DOTFILES/bin/host-specific/nixnode/volume-osd up
bindsym XF86AudioMute exec --no-startup-id $DOTFILES/bin/host-specific/nixnode/volume-osd toggle
bindsym XF86AudioMicMute exec --no-startup-id $DOTFILES/bin/host-specific/nixnode/mic-mute-toggle
bindsym XF86MonBrightnessDown exec --no-startup-id $DOTFILES/bin/host-specific/coregate/brightness-osd 5%-
bindsym XF86MonBrightnessUp exec --no-startup-id $DOTFILES/bin/host-specific/coregate/brightness-osd +5%
