exec --no-startup-id $DOTFILES/bin/sway-idle-lock-manager
exec_always --no-startup-id sh -c 'pgrep -xu "$USER" spice-vdagent >/dev/null || exec spice-vdagent'
exec_always --no-startup-id $DOTFILES/bin/waycorner-start
exec_always --no-startup-id $DOTFILES/bin/cliphist-daemon
