exec --no-startup-id $DOTFILES/bin/sway-idle-lock-manager
exec --no-startup-id $DOTFILES/bin/host-specific/nextgate/keyless-start
exec --no-startup-id $DOTFILES/bin/host-specific/nextgate/optical-audio-default
exec_always --no-startup-id $DOTFILES/bin/waycorner-start
exec_always --no-startup-id systemctl --user restart streamdeck-controls.service
exec_always --no-startup-id $DOTFILES/bin/cliphist-daemon
