bindsym $mod+Shift+s exec --no-startup-id flameshot gui -c -p ~/screenshots
bindsym $mod+Shift+g exec --no-startup-id /home/doug/dotfiles/bin/telegram-with-browser
bindsym $mod+Shift+u exec --no-startup-id /home/doug/dotfiles/bin/unifi-camera-menu
bindsym $mod+Shift+f exec --no-startup-id $terminal_cmd yazi /home/doug
bindsym $mod+Shift+o exec --no-startup-id /home/doug/dotfiles/bin/2fas-otp-popup
bindsym $mod+Shift+equal exec --no-startup-id galculator
bindsym $mod+Control+space exec --no-startup-id /home/doug/dotfiles/bin/emoji-picker
bindsym $mod+Control+v exec --no-startup-id /home/doug/dotfiles/bin/clipboard-popup
bindsym $mod+Shift+m exec --no-startup-id /home/doug/dotfiles/bin/google-messages
bindsym $mod+Control+Shift+w exec --no-startup-id /home/doug/dotfiles/bin/wallpaper-rotate --select
bindsym $mod+Shift+i exec --no-startup-id $terminal_cmd impala
bindsym $mod+Shift+x kill
bindsym $mod+Shift+n exec --no-startup-id /home/doug/dotfiles/bin/renix-popup
bindsym $mod+Shift+Escape exec --no-startup-id /home/doug/dotfiles/bin/sway-display-sleep
