font $sway_font
floating_modifier $mod
default_orientation horizontal
default_border pixel 1
default_floating_border pixel 1

seat * xcursor_theme Adwaita 24
seat seat0 hide_cursor when-typing enable

input type:keyboard {
    repeat_delay 200
}

# Last selected wallpaper, maintained by wallpaper-rotate.
include ~/.local/state/sway-wallpaper.conf
