for_window [title="^renix-popup$"] floating enable, resize set 1200 800, move position center, focus
for_window [app_id="clipboard-popup"] floating enable, resize set 1500 900, move position center, focus
for_window [class="clipboard-popup"] floating enable, resize set 1500 900, move position center, focus
for_window [app_id="^[Kk]eymapp$"] floating enable
for_window [class="^[Kk]eymapp$"] floating enable
for_window [title="^Keymapp$"] floating enable
for_window [title="Google Messages for web: Conversations"] title_format "Messages"
for_window [app_id="gsimplecal"] floating enable, border pixel 0, move position mouse, move up 21 px, focus
